import {PUZZLES,feedback,dayKey,puzzleIndex,validSave} from './token-engine.mjs';
const $=id=>document.getElementById(id),root=$('game');let day=dayKey(),mode='daily',draft='',practiceNumber=0,notice='',reveal=false;
const fresh=()=>({day,guesses:[],hints:0});let daily=fresh(),practice=fresh(),stats={wins:[]};
try{const saved=JSON.parse(localStorage.getItem('next-token-v1'));if(validSave(saved,day))daily=saved;const s=JSON.parse(localStorage.getItem('next-token-stats-v1'));if(s&&Array.isArray(s.wins))stats.wins=s.wins.filter(d=>/^\d{4}-\d{2}-\d{2}$/.test(d));}catch{}
if(window.parent!==window)document.body.classList.add('embedded');
let practiceIndex=0;
function state(){return mode==='daily'?daily:practice;}function puzzle(){return PUZZLES[mode==='daily'?puzzleIndex(day):practiceIndex];}function won(){return state().guesses.includes(puzzle()[0]);}function ended(){return won()||state().guesses.length===6;}
function store(){try{localStorage.setItem('next-token-v1',JSON.stringify(daily));localStorage.setItem('next-token-stats-v1',JSON.stringify(stats));}catch{}}
function streak(){let d=new Date(day+'T00:00:00Z'),n=0;if(!stats.wins.includes(day))d.setUTCDate(d.getUTCDate()-1);while(stats.wins.includes(dayKey(d))){n++;d.setUTCDate(d.getUTCDate()-1);}return n;}
// Measure the content, not the iframe viewport, so opening hints can both grow and shrink it.
function resize(){try{const frame=window.frameElement;if(frame)frame.style.height=(Math.ceil(root.getBoundingClientRect().height)+12)+'px';}catch{}}
new ResizeObserver(resize).observe(root);
function render(){const s=state(),p=puzzle(),len=p[0].length,done=ended();root.style.setProperty('--letters',len);$('daily').setAttribute('aria-pressed',mode==='daily');$('practice').setAttribute('aria-pressed',mode==='practice');$('puzzle-id').textContent=mode==='daily'?day+' · '+len+' letters':'Practice '+(practiceNumber+1)+' · '+len+' letters';$('streak').textContent=streak()+' day streak';$('category').textContent=p[1];$('clue').textContent=p[2];
 $('board').replaceChildren();const keys={};
 for(let row=0;row<6;row++){const el=document.createElement('div');el.className='row'+(reveal&&row===s.guesses.length-1?' reveal':'');const word=s.guesses[row]||(row===s.guesses.length?draft:'');const marks=s.guesses[row]?feedback(word,p[0]):[];el.setAttribute('aria-label',s.guesses[row]?'Guess '+(row+1)+': '+word:'Guess '+(row+1));for(let i=0;i<len;i++){const tile=document.createElement('span');tile.className='tile'+(marks[i]?' '+marks[i]:word[i]?' filled':'');tile.style.setProperty('--i',i);tile.textContent=word[i]||'';if(marks[i]){const labels={exact:'right spot',present:'wrong spot',absent:'not in answer'},symbols={exact:'✓',present:'↔',absent:'·'};tile.setAttribute('aria-label',word[i]+': '+labels[marks[i]]);const mark=document.createElement('small');mark.textContent=symbols[marks[i]];mark.setAttribute('aria-hidden','true');tile.append(mark);const rank={absent:1,present:2,exact:3};if(!keys[word[i]]||rank[marks[i]]>rank[keys[word[i]]])keys[word[i]]=marks[i];}el.append(tile);}$('board').append(el);}
 reveal=false;document.querySelectorAll('.key').forEach(k=>{k.className='key'+(k.dataset.key.length>1?' wide':'')+(keys[k.dataset.key]?' '+keys[k.dataset.key]:'');k.disabled=done;});
 $('status').textContent=notice||(!s.guesses.length?'Start with any '+len+'-letter guess.':'');$('hint').disabled=done||s.hints===2;$('hint').textContent=s.hints===2?'Both hints revealed':s.hints?'One more hint?':'Need a hint?';$('clear').disabled=done||!draft;
 $('hints').replaceChildren();for(let i=0;i<s.hints;i++){const hint=document.createElement('p');hint.className='hint';hint.textContent=p[3+i];$('hints').append(hint);}
 $('result').hidden=!done;
 if(done){$('result-title').textContent=won()?['First try. Nice.','That clicked.','Nicely worked out.','You found it.','Worth sticking with.','Right on time.'][s.guesses.length-1]:'A new one for next time.';$('explanation').replaceChildren();const answer=document.createElement('strong');answer.className='answer';answer.textContent=p[0]+'. ';$('explanation').append(answer,document.createTextNode((p[3]+' '+p[4]).replace(/_{3,}/g,p[0].toLowerCase())));$('again').textContent=mode==='daily'?'Keep playing in practice':'Next word';$('next-puzzle').textContent=mode==='daily'?'Same daily word for everyone. Come back tomorrow for a new one.':'Practice does not change your daily result or streak.';}
}
function updateDay(){const today=dayKey();if(today!==day){day=today;daily=fresh();if(mode==='daily'){draft='';notice='A new daily puzzle is ready.';render();}}}
function submit(){updateDay();if(ended())return;const s=state(),answer=puzzle()[0];if(draft.length!==answer.length){notice='You need '+answer.length+' letters.';render();return;}if(s.guesses.includes(draft)){notice='Already tried that. Try a different guess.';render();return;}s.guesses.push(draft);draft='';reveal=true;notice='';if(ended()){if(mode==='daily'&&won()&&!stats.wins.includes(day))stats.wins.push(day);notice=won()?'Solved in '+s.guesses.length+' of 6.':'The answer was '+answer+'.';}else if(s.guesses.length===2&&!s.hints)notice='Stuck? There’s a hint below the keyboard.';store();render();}
function key(value){updateDay();if(ended())return;notice='';if(value==='ENTER'){submit();return;}if(value==='BACKSPACE')draft=draft.slice(0,-1);else if(/^[A-Z]$/.test(value)&&draft.length<puzzle()[0].length)draft+=value;render();}
for(const letters of ['QWERTYUIOP','ASDFGHJKL','ENTER ZXCVBNM BACKSPACE']){const row=document.createElement('div');row.className='keyrow';const list=letters.includes(' ')?['ENTER',...'ZXCVBNM','BACKSPACE']:[...letters];for(const letter of list){const b=document.createElement('button');b.className='key';b.dataset.key=letter;b.textContent=letter==='BACKSPACE'?'⌫':letter==='ENTER'?'Guess':letter;b.setAttribute('aria-label',letter==='BACKSPACE'?'Delete letter':letter==='ENTER'?'Submit guess':letter);b.addEventListener('click',()=>{key(letter);root.focus({preventScroll:true});});row.append(b);}$('keyboard').append(row);}
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target.tagName==='TEXTAREA')return;if(e.key==='Enter'&&['BUTTON','SUMMARY','A'].includes(e.target.tagName))return;const value=e.key==='Enter'?'ENTER':e.key==='Backspace'?'BACKSPACE':e.key.toUpperCase();if(value==='ENTER'||value==='BACKSPACE'||/^[A-Z]$/.test(value)){e.preventDefault();key(value);}});
$('hint').addEventListener('click',()=>{if(!ended()&&state().hints<2){state().hints++;notice='Hint revealed below.';store();render();}});$('clear').addEventListener('click',()=>{draft='';notice='';render();root.focus({preventScroll:true});});
function changeMode(next){updateDay();mode=next;draft='';notice='';$('share-text').hidden=true;render();}
$('daily').addEventListener('click',()=>changeMode('daily'));$('practice').addEventListener('click',()=>changeMode('practice'));
$('again').addEventListener('click',()=>{if(mode==='daily'){changeMode('practice');if(!ended()){root.scrollIntoView({block:'start'});return;}}practiceNumber++;practiceIndex=(practiceIndex+1+Math.floor(Math.random()*(PUZZLES.length-1)))%PUZZLES.length;practice=fresh();draft='';notice='';$('share-text').hidden=true;render();root.focus({preventScroll:true});});
$('share').addEventListener('click',async()=>{const s=state(),p=puzzle();const text='Next Token · '+(mode==='daily'?day:'Practice')+'\n'+(won()?s.guesses.length:'X')+'/6 · '+s.hints+' hint'+(s.hints===1?'':'s')+'\n\n'+s.guesses.map(g=>feedback(g,p[0]).map(m=>({exact:'🟩',present:'🟨',absent:'⬜'})[m]).join('')).join('\n')+'\n\nlouisai.co.uk/token.html';try{await navigator.clipboard.writeText(text);notice='Result copied. No spoilers.';}catch{$('share-text').hidden=false;$('share-text').value=text;$('share-text').focus();$('share-text').select();notice='Select and copy your result below.';}render();});
setInterval(updateDay,60000);render();


